export const COLLECTIONS = {
  users: "users",
  restaurants: "restaurants",
  restaurantClaims: "restaurantClaims",
  restaurantPolicies: "restaurantPolicies",
  diners: "diners",
  reservations: "reservations",
  waitlistCandidates: "waitlistCandidates",
  recoveryRequests: "recoveryRequests",
  agentRuns: "agentRuns",
  agentLogs: "agentLogs",
  auditLogs: "auditLogs",
  externalIntegrations: "externalIntegrations",
  sponsorEvents: "sponsorEvents",
  notificationEvents: "notificationEvents",
  importedRestaurantSources: "importedRestaurantSources",
} as const;

export const DEMO_USERS = [
  {
    _id: "user_sofia",
    authProvider: "demo",
    authProviderId: "demo:sofia",
    email: "sofia@restauranty.demo",
    name: "Sofia Martinez",
    role: "restaurant_manager",
  },
  {
    _id: "user_daniel",
    authProvider: "demo",
    authProviderId: "demo:daniel",
    email: "daniel@restauranty.demo",
    name: "Daniel Park",
    role: "diner",
  },
  {
    _id: "user_maya",
    authProvider: "demo",
    authProviderId: "demo:maya",
    email: "maya@restauranty.demo",
    name: "Maya Chen",
    role: "replacement_diner",
  },
  {
    _id: "user_admin",
    authProvider: "demo",
    authProviderId: "demo:admin",
    email: "admin@restauranty.demo",
    name: "Admin Demo",
    role: "admin",
  },
] as const;

export const REQUIRED_ENV = ["MONGODB_URI", "MONGODB_DB"] as const;

export const ALL_ENV_KEYS = [
  "MONGODB_URI",
  "MONGODB_DB",
  "GOOGLE_MAPS_API_KEY",
  "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY",
  "AUTH0_SECRET",
  "APP_BASE_URL",
  "AUTH0_DOMAIN",
  "AUTH0_CLIENT_ID",
  "AUTH0_CLIENT_SECRET",
  "AUTH0_AUDIENCE",
  "AUTH0_SCOPE",
  "WORLD_ID_APP_ID",
  "WORLD_ID_ACTION_ID",
  "WORLD_ID_SECRET_KEY",
  "NEXT_PUBLIC_WORLD_ID_APP_ID",
  "NEXT_PUBLIC_WORLD_ID_ACTION_ID",
  "TWILIO_ACCOUNT_SID",
  "TWILIO_AUTH_TOKEN",
  "TWILIO_PHONE_NUMBER",
  "TWILIO_VERIFY_SERVICE_SID",
  "FETCH_AGENTVERSE_KEY",
  "AGENTVERSE_MAILBOX_KEY",
  "AGENTVERSE_AGENT_ADDRESS",
  "AGENTVERSE_AGENT_NAME",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "GOOGLE_API_KEY",
  "GEMMA_API_KEY",
  "ELEVENLABS_API_KEY",
  "ELEVENLABS_VOICE_ID",
  "CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET",
  "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME",
  "ENABLE_REAL_SMS",
  "ENABLE_AGENTVERSE_SYNC",
  "ENABLE_AGENTVERSE_CHAT",
  "ENABLE_LLM_EXPLANATIONS",
  "ENABLE_WORLD_ID",
  "ENABLE_ELEVENLABS",
  "ENABLE_CLOUDINARY",
  "ENABLE_GOOGLE_PLACES",
  "ENABLE_AUTH0",
] as const;

export const DEFAULT_FLAGS = {
  ENABLE_REAL_SMS: false,
  ENABLE_AGENTVERSE_SYNC: false,
  ENABLE_AGENTVERSE_CHAT: true,
  ENABLE_LLM_EXPLANATIONS: false,
  ENABLE_WORLD_ID: true,
  ENABLE_ELEVENLABS: false,
  ENABLE_CLOUDINARY: false,
  ENABLE_GOOGLE_PLACES: true,
  ENABLE_AUTH0: true,
} as const;
