import type {
  AgentLog,
  AgentRun,
  AuditLog,
  Diner,
  RecoveryRequest,
  Reservation,
  Restaurant,
  RestaurantPolicy,
  SponsorEvent,
  User,
  WaitlistCandidate,
} from "@/lib/types";
import { DEMO_USERS } from "@/lib/constants";

const now = "2026-04-26T00:00:00.000Z";

const stamp = { createdAt: now, updatedAt: now };

export const seedUsers: User[] = DEMO_USERS.map((user) => ({
  ...user,
  ...stamp,
})) as User[];

export const seedRestaurants: Restaurant[] = [
  {
    _id: "rest_katsuya",
    source: "seed",
    externalIds: { googlePlaceId: "seed-katsuya-west-hollywood" },
    name: "Katsuya West Hollywood",
    cuisineCategories: ["sushi", "japanese", "high-demand"],
    phone: "+13236556767",
    website: "https://restauranty.demo/katsuya",
    imageUrl:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80",
    rating: 4.5,
    reviewCount: 1860,
    price: "$$$",
    address: "6300 Hollywood Blvd, Los Angeles, CA",
    coordinates: { lat: 34.1016, lng: -118.3267 },
    averageCheck: 90,
    neighborhood: "West Hollywood",
    ownerUserId: "user_sofia",
    ...stamp,
  },
  {
    _id: "rest_bestia",
    source: "seed",
    externalIds: { googlePlaceId: "seed-bestia" },
    name: "Bestia",
    cuisineCategories: ["italian", "arts district"],
    phone: "+12135145724",
    imageUrl:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
    rating: 4.6,
    reviewCount: 4200,
    price: "$$$",
    address: "2121 E 7th Pl, Los Angeles, CA",
    coordinates: { lat: 34.0336, lng: -118.2295 },
    averageCheck: 105,
    neighborhood: "Arts District",
    ownerUserId: "user_sofia",
    ...stamp,
  },
  {
    _id: "rest_republique",
    source: "seed",
    externalIds: { googlePlaceId: "seed-republique" },
    name: "Republique",
    cuisineCategories: ["french", "california"],
    phone: "+13103626110",
    rating: 4.7,
    reviewCount: 3500,
    price: "$$$",
    address: "624 S La Brea Ave, Los Angeles, CA",
    coordinates: { lat: 34.0634, lng: -118.3441 },
    averageCheck: 82,
    neighborhood: "Hancock Park",
    ownerUserId: "user_sofia",
    ...stamp,
  },
];

export const seedPolicies: RestaurantPolicy[] = seedRestaurants.map((restaurant) => ({
  _id: `policy_${restaurant._id}`,
  restaurantId: restaurant._id,
  confirmationWindowHours: 3,
  finalConfirmationMinutes: 15,
  waitlistRefillEnabled: true,
  peerTransferAllowed: false,
  paidResaleAllowed: false,
  restaurantApprovalRequired: true,
  maxTransferFee: 0,
  feeWaiverIfRefilled: true,
  humanVerificationRequired: true,
  suspiciousAccountAutoReview: true,
  noShowGraceMinutes: 10,
  autoReleaseAfterGracePeriod: false,
  managerApprovalPhone: "+13235550124",
  ...stamp,
}));

export const seedDiners: Diner[] = [
  {
    _id: "diner_daniel",
    userId: "user_daniel",
    name: "Daniel Park",
    phone: "+13235550101",
    email: "daniel@restauranty.demo",
    verifiedHuman: true,
    worldIdNullifierHash: "demo_nullifier_daniel",
    noShowCount: 0,
    lateCancellationCount: 1,
    completedReservations: 14,
    activeReservations: 1,
    trustScore: 81,
    preferredCuisines: ["sushi", "japanese", "italian"],
    homeCoordinates: { lat: 34.09, lng: -118.36 },
    ...stamp,
  },
  {
    _id: "diner_maya",
    userId: "user_maya",
    name: "Maya Chen",
    phone: "+13235550102",
    email: "maya@restauranty.demo",
    verifiedHuman: true,
    worldIdNullifierHash: "demo_nullifier_maya",
    noShowCount: 0,
    lateCancellationCount: 0,
    completedReservations: 8,
    activeReservations: 0,
    trustScore: 94,
    preferredCuisines: ["sushi", "japanese"],
    homeCoordinates: { lat: 34.095, lng: -118.34 },
    ...stamp,
  },
  {
    _id: "diner_jordan",
    name: "Jordan Lee",
    phone: "+13235550103",
    email: "jordan@restauranty.demo",
    verifiedHuman: true,
    noShowCount: 0,
    lateCancellationCount: 0,
    completedReservations: 6,
    activeReservations: 0,
    trustScore: 88,
    preferredCuisines: ["japanese", "korean"],
    homeCoordinates: { lat: 34.08, lng: -118.32 },
    ...stamp,
  },
  {
    _id: "diner_alex",
    name: "Alex Kim",
    phone: "+13235550104",
    email: "alex@restauranty.demo",
    verifiedHuman: false,
    noShowCount: 1,
    lateCancellationCount: 2,
    completedReservations: 1,
    activeReservations: 3,
    trustScore: 42,
    preferredCuisines: ["sushi"],
    homeCoordinates: { lat: 34.12, lng: -118.41 },
    ...stamp,
  },
];

export const seedReservations: Reservation[] = [
  {
    _id: "res_katsuya_815",
    restaurantId: "rest_katsuya",
    dinerId: "diner_daniel",
    source: "seed",
    date: "2026-04-26",
    startTime: "20:15",
    partySize: 2,
    status: "unconfirmed",
    confirmationStatus: "ignored",
    reminderOpened: false,
    reminderSentAt: "2026-04-25T20:15:00.000Z",
    priorLateCancellationsAtBooking: 1,
    priorNoShowsAtBooking: 0,
    cardOnFile: true,
    bookedAt: "2026-04-15T18:24:00.000Z",
    highDemandSlot: true,
    estimatedRevenue: 180,
    cancellationFee: 40,
    riskScore: 82,
    riskLevel: "critical",
    recommendedAction: "send final confirmation and prepare waitlist recovery",
    recoveryStatus: "ready",
    ...stamp,
  },
  {
    _id: "res_bestia_900",
    restaurantId: "rest_bestia",
    dinerId: "diner_jordan",
    source: "seed",
    date: "2026-04-26",
    startTime: "21:00",
    partySize: 4,
    status: "unconfirmed",
    confirmationStatus: "requested",
    reminderOpened: false,
    priorLateCancellationsAtBooking: 0,
    priorNoShowsAtBooking: 0,
    cardOnFile: false,
    bookedAt: "2026-04-20T14:04:00.000Z",
    highDemandSlot: true,
    estimatedRevenue: 410,
    cancellationFee: 60,
    riskScore: 58,
    riskLevel: "medium",
    recommendedAction: "monitor",
    recoveryStatus: "monitoring",
    ...stamp,
  },
  {
    _id: "res_republique_730",
    restaurantId: "rest_republique",
    dinerId: "diner_alex",
    source: "seed",
    date: "2026-04-26",
    startTime: "19:30",
    partySize: 2,
    status: "released_by_diner",
    confirmationStatus: "declined",
    reminderOpened: true,
    priorLateCancellationsAtBooking: 2,
    priorNoShowsAtBooking: 1,
    cardOnFile: false,
    bookedAt: "2026-04-22T12:00:00.000Z",
    highDemandSlot: true,
    estimatedRevenue: 165,
    cancellationFee: 40,
    riskScore: 95,
    riskLevel: "critical",
    recommendedAction: "activate waitlist recovery",
    recoveryStatus: "active",
    ...stamp,
  },
];

export const seedWaitlistCandidates: WaitlistCandidate[] = [
  {
    _id: "wait_maya_katsuya",
    dinerId: "diner_maya",
    restaurantId: "rest_katsuya",
    desiredDate: "2026-04-26",
    desiredTimeWindowStart: "19:30",
    desiredTimeWindowEnd: "21:30",
    partySize: 2,
    distanceMiles: 1.4,
    cuisineMatchScore: 98,
    arrivalEtaMinutes: 18,
    verifiedHuman: true,
    commitmentLevel: "deposit_ready",
    priorityScore: 96,
    status: "available",
    ...stamp,
  },
  {
    _id: "wait_jordan_katsuya",
    dinerId: "diner_jordan",
    restaurantId: "rest_katsuya",
    desiredDate: "2026-04-26",
    desiredTimeWindowStart: "19:00",
    desiredTimeWindowEnd: "21:45",
    partySize: 2,
    distanceMiles: 2.1,
    cuisineMatchScore: 86,
    arrivalEtaMinutes: 24,
    verifiedHuman: true,
    commitmentLevel: "quick_confirm",
    priorityScore: 91,
    status: "available",
    ...stamp,
  },
  {
    _id: "wait_alex_katsuya",
    dinerId: "diner_alex",
    restaurantId: "rest_katsuya",
    desiredDate: "2026-04-26",
    desiredTimeWindowStart: "19:00",
    desiredTimeWindowEnd: "22:00",
    partySize: 2,
    distanceMiles: 4.5,
    cuisineMatchScore: 78,
    arrivalEtaMinutes: 35,
    verifiedHuman: false,
    commitmentLevel: "browsing",
    priorityScore: 42,
    status: "available",
    ...stamp,
  },
];

export const seedRecoveryRequests: RecoveryRequest[] = [
  {
    _id: "recovery_katsuya_815",
    reservationId: "res_katsuya_815",
    restaurantId: "rest_katsuya",
    originalDinerId: "diner_daniel",
    selectedReplacementDinerId: "diner_maya",
    status: "manager_approval_required",
    revenueProtected: 180,
    feeWaived: false,
    startedAt: "2026-04-26T17:12:00.000Z",
    ...stamp,
  },
];

export const seedAgentRuns: AgentRun[] = [
  {
    _id: "run_katsuya_815",
    recoveryRequestId: "recovery_katsuya_815",
    reservationId: "res_katsuya_815",
    status: "completed",
    agentsInvoked: ["RiskAgent", "PolicyAgent", "WaitlistAgent", "FairnessAgent"],
    inputSnapshot: { reservationId: "res_katsuya_815" },
    outputSnapshot: { riskScore: 82, topCandidate: "diner_maya" },
    createdAt: "2026-04-26T17:12:00.000Z",
    completedAt: "2026-04-26T17:13:00.000Z",
  },
];

export const seedAgentLogs: AgentLog[] = [
  {
    _id: "log_risk_1",
    agentRunId: "run_katsuya_815",
    reservationId: "res_katsuya_815",
    agentName: "RiskAgent",
    message: "Scored reservation 82/100 due to ignored confirmation and proximity to seating.",
    severity: "warning",
    status: "completed",
    createdAt: "2026-04-26T17:12:10.000Z",
  },
  {
    _id: "log_waitlist_1",
    agentRunId: "run_katsuya_815",
    reservationId: "res_katsuya_815",
    agentName: "WaitlistAgent",
    message: "Ranked Maya Chen as top verified replacement diner.",
    severity: "success",
    status: "completed",
    createdAt: "2026-04-26T17:12:42.000Z",
  },
];

export const seedAuditLogs: AuditLog[] = [
  {
    _id: "audit_seed_1",
    actorType: "system",
    actorId: "seed",
    action: "seed_demo_data",
    entityType: "system",
    entityId: "restauranty",
    metadata: { source: "seed-data" },
    createdAt: now,
  },
];

export const seedSponsorEvents: SponsorEvent[] = [
  {
    _id: "sponsor_figma_seed",
    sponsor: "figma",
    eventType: "claude_design_specs_referenced",
    payload: { files: 14 },
    createdAt: now,
  },
  {
    _id: "sponsor_cognition_seed",
    sponsor: "cognition",
    eventType: "deterministic_agents_enabled",
    payload: { agents: ["RiskAgent", "PolicyAgent", "WaitlistAgent", "FairnessAgent"] },
    createdAt: now,
  },
];

export const seedDataset = {
  users: seedUsers,
  restaurants: seedRestaurants,
  restaurantPolicies: seedPolicies,
  diners: seedDiners,
  reservations: seedReservations,
  waitlistCandidates: seedWaitlistCandidates,
  recoveryRequests: seedRecoveryRequests,
  agentRuns: seedAgentRuns,
  agentLogs: seedAgentLogs,
  auditLogs: seedAuditLogs,
  sponsorEvents: seedSponsorEvents,
};
